### ISSUE TITLE
the program doesn't run

### ISSUE THREAD

**Issue by rioxrenato** [hahagu/WindowsThumbnailGenerator#1]
I just open it, nothing happens and that's all

**Comment by hahagu** [comment]
Do you have .NET 5 installed?
If so, what is your windows version/build?

**Comment by hahagu** [comment]
The program has been fixed.

**Comment by maaldheefee** [comment]
I have the same issue, with the latest release (v3.0.0 GUI version). When I open it, nothing happens. But the process remains suspended in Task Manager.

.NET 5.0 Desktop Runtime (v5.0.9)
Windows 11 build 22000.132

**Comment by hahagu** [comment]
> I have the same issue, with the latest release (v3.0.0 GUI version). When I open it, nothing happens. But the process remains suspended in Task Manager.
> 
> .NET 5.0 Desktop Runtime (v5.0.9)
> Windows 11 build 22000.132

Hello, it seems that Visual Studio's trimming feature was the culprit.
I have now updated the release files.
Please re-download and try again!

Thanks!

**Comment by maaldheefee** [comment]
Works now. Thanks.

**Comment by hahagu** [comment]
I will now close this issue, as it has been solved :)
