### ISSUE TITLE
Rollback possible?

### ISSUE THREAD

**Issue by mistergom** [hahagu/WindowsThumbnailGenerator#11]
Hello!
Is-it possible to rollback? With recursive effect?
I think that Windows Thumbnail Generator creates a desktop.ini file in each folder + 1 ico image file.
Best!

**Comment by dimitrissot** [comment]
Hi, If you want to delete all the folder thumbnails that are generated by WindowsThumbnailGenerator
 you have to:

1.  Go to folder otions in windows explorer and tick show hidden files and folders and also untick the hide protected operating system files (see screenshot)
2.  Search in the folders or root folder that you want the thumbnails to be removed for: **desktop.ini** and delete all of them
3.  Search again at the same folders for: **thumb.ico** and delete all of them
Then your folders - root folder with all the other folders inside will have the default icon again

![Screenshot_1](https://user-images.githubusercontent.com/92344176/137955243-4c2eb1c8-d852-4517-8fca-5a8ded4cf3ab.jpg)

Cheers!

**Comment by mistergom** [comment]
Thanks! Sounds good and works well ;)

**Comment by hahagu** [comment]
Will add this feature at next major release.
