### ISSUE TITLE
Please, make it work with folder.jpg

### ISSUE THREAD

**Issue by SgtPepperman** [hahagu/WindowsThumbnailGenerator#14]
Thank your for this wonderful tool, since Microsoft is taking so long to fix that issue, if they will ever do it.

I don't know how hard it is to do; but it would be nice to have the option to work with _folder.jpg_, like converting those specific images to icons; more or less as an option to customise the folders' appearance.

**Comment by hahagu** [comment]
https://github.com/hahagu/WindowsThumbnailGenerator/issues/6
Duplicate
