### ISSUE TITLE
Feature Request: PDF Support for Folder Thumbnail

### ISSUE THREAD

**Issue by PaladinQuinn** [hahagu/WindowsThumbnailGenerator#15]
As I upgraded my PC I have ended up with Windows 11 and I miss having PDF files show up in Folder Thumbnail, can you add support for them? I do hope I am doing this right as I just joined to ask this.

**Comment by hahagu** [comment]
I will see if that is available within the libraries I am using.
If it is, I will make sure to include it on the next version :)

**Comment by PaladinQuinn** [comment]
Thanks for getting back on this. <3 - be sure to tell me if it's possible.

**Comment by hahagu** [comment]
Will do :)

**Comment by hahagu** [comment]
Closing as it was deemed not possible with current implementation, unfortunately.

Will try to work on it if I get to it. :)
