### ISSUE TITLE
Remove thumbnails and start fresh

### ISSUE THREAD

**Issue by cableghost** [hahagu/WindowsThumbnailGenerator#19]
How might one clean out all thumbnails and start over (not using the clear cache option). If I decide to not want thumbnails for some directories. I can see why MS changed its focus, because having thumbnails takes a lot of cycles to show and would like to remove them from some of those directories.

**Comment by hahagu** [comment]
I haven't implemented a "clear" function yet, but it is due next update.

However, I haven't been able to work on the project because this is just a side project for me, and I currently have other jobs that I do for a living haha.

Meanwhile, you can open your CMD as administrator,
`cd` to the directory you want to clear, and run these two commands.
`del /s /a desktop.ini`
`del /s /a thumb.ico`

This will clear all folders of the thumbnails.

**Comment by salehDolle** [comment]
I need your help, it did not work for me on folders on D:\ drive, I get this error:
1:
Remove-Item : A positional parameter cannot be found that accepts argument '/a'.
At line:1 char:1
+ del /s /a desktop.ini
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

2:
Remove-Item : A positional parameter cannot be found that accepts argument '/a'.
At line:1 char:1
+ del /s /a thumb.ico
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by salehDolle** [comment]
thank you in advance for making this amazing tool :) 
but I have a Q:
can I choose different icon to generate than the one you put on the (WindowsThumbnailGenerator) tool?

**Comment by hahagu** [comment]
> I need your help, it did not work for me on folders on D:\ drive, I get this error: 1: Remove-Item : A positional parameter cannot be found that accepts argument '/a'. At line:1 char:1
> 
>     * del /s /a desktop.ini
> 
>     * ```
>         + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
>         + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
>       ```
> 
> 
> 2: Remove-Item : A positional parameter cannot be found that accepts argument '/a'. At line:1 char:1
> 
>     * del /s /a thumb.ico
> 
>     * ```
>         + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
>         + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
>       ```

Use CMD, not powershell

**Comment by hahagu** [comment]
> thank you in advance for making this amazing tool :) but I have a Q: can I choose different icon to generate than the one you put on the (WindowsThumbnailGenerator) tool?

Not as of now, unless you compile the tool on your own, using a different icon.

I had plans, but the project is not being worked on as of now, as I'm much busier now.

And, Windows 11 already has support for folder thumbnails now, so I have not much reason to continue the development of the tool, besides the customization factor, which this tool wasn't really aimed to do in the first place.

**Comment by salehDolle** [comment]
thank you I appreciate your quick replay and I wish you success in your life and projects:
when I run (cd D:\) on powershell it work, but on CMD it won't take me to the direction.

**Comment by hahagu** [comment]
> 

Just run `D:` instead of `cd D:`

That's how you move in drives on CMD.

**Comment by salehDolle** [comment]
you are awesome, it worked like a charm, thank you again and I'm sorry to interrupted you, good luck :)
