### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by Suleman-Elahi** [hahagu/WindowsThumbnailGenerator#2]
![image](https://user-images.githubusercontent.com/24384996/129320678-57d966ba-337b-4942-9406-0ea39c1a72cb.png)

It says it needs .Net run time, I have installed it but still won't launch. Keep throwing the same error, even when I have .Net RunTime INstaled from here: https://dotnet.microsoft.com/download/dotnet/5.0/runtime?utm_source=getdotnetcore&utm_medium=referral

**Comment by hahagu** [comment]
The executable is to be packaged standalone from the next version.
This will solve all dependency errors.
Version 3.0.0 is released now.

Also, it seems you have installed .NET 5.0 Runtime, not .NET 5.0 Desktop Runtime.
Please install the correct version!

Thanks!

**Comment by hahagu** [comment]
It is now released.
Please test :)

**Comment by hahagu** [comment]
Also, please make sure you have installed .NET desktop runtime, and not the .NET runtime.

**Comment by hahagu** [comment]
I will now be closing this, as installing the correct .NET will solve the issue.
