### ISSUE TITLE
Clearer documentation in wiki for installation

### ISSUE THREAD

**Issue by HeroicMeaning** [hahagu/WindowsThumbnailGenerator#22]
Currently, it says in the wiki that you should 
"Download the application from the [Releases page](https://github.com/hahagu/WindowsThumbnailGenerator/releases)."

on that page, there exists 
a zip file for the source code
a zip file for "publish"
and a zip file for "publish console"

WHICH of these "applications" should we download and install?
what are the differences between them?

**Comment by hahagu** [comment]
Source code zips are generated automatically by GitHub.
I believe stating that downloads can be obtained from the "Releases" page is standard practice :)
However, I do understand where that confusion might come from, especially if someone is new to GitHub.

The source code zip is the source for the application, from the commit where the release happened.

Also, what I should have stated is that `Publish.zip` is for the GUI,
while the `Publish-Console.zip` is for console usage.

I think I will add that :)
Thanks for the feedback!
