### ISSUE TITLE
Thumbnail choice

### ISSUE THREAD

**Issue by cherryred02** [hahagu/WindowsThumbnailGenerator#23]
I know this is not new and see that someone requested to choose with folder.jpg/gif. But I'm wondering if there is a way to work around that for the moment. How does the generator choose the file for thumbnail? I was trying to see if it was choosing by most recent file but that does not seem to work. Seems to be random or does anyone know?

**Comment by hahagu** [comment]
https://github.com/hahagu/WindowsThumbnailGenerator/blob/0213bd40a79bb3773bd7a07e9b1b573f324d7cf1/Library/ProcessHandler.cs#L62-L65

`Directory.GetFiles()` will return the files in the order that the filesystem returns them in.

Thanks.
