### ISSUE TITLE
Any chance about new updates?

### ISSUE THREAD

**Issue by ghost** [hahagu/WindowsThumbnailGenerator#25]
I know it's probably hard to create a software like this and since it's the only one available online too. But any chance it can have 2 most wanted improvements like **applying it at once for all folders and making a better preview thumbnail**?

**Comment by hahagu** [comment]
Sorry, still short on time I'm afraid 😅 

Pull requests are welcome.

However, I do not understand what you mean by "applying all at once" and "making a better preview thumbnail"?

"Better" is a subjective term, and quite honestly, I think the current design looks pretty good, and does not need to change.

Also, the "recursive" option will apply to all directories inside the chosen directory.

**Comment by ghost** [comment]
> Sorry, still short on time I'm afraid 😅
> 
> Pull requests are welcome.
> 
> However, I do not understand what you mean by "applying all at once" and "making a better preview thumbnail"?
> 
> "Better" is a subjective term, and quite honestly, I think the current design looks pretty good, and does not need to change.
> 
> Also, the "recursive" option will apply to all directories inside the chosen directory.

Hi hahagu, thanks for your reply.

By the two tips I mean :

### **#1 The folder thumbnail could be similar to Windows 10 Version**

W10 Version
<img width="164" alt="W10 Folder Thumbnail2" src="https://user-images.githubusercontent.com/42815200/193809512-ad405282-daa2-4913-b812-b4485b5a40f2.png">

WindowsThumbnailGnerator Version
<img width="164" alt="W11 Folder Thumbnail" src="https://user-images.githubusercontent.com/42815200/193809528-55590c5b-93d1-4ca5-a8c6-e4f21ac110d4.png">

I really aprecciate the design wich is actually better but it doesnt show a lot of the picture preview like the W10 model. 

And 
### **#2 Applying all at once instead of aplying one by one**

As far as I watched the tutorials and applied the model, I need to aply it for every single folder, instead it maybe could be done at once, like for every folder with pictures it could be aplied instead of doing it one by one. 

**Again this is just my opinion also because Iam still not capable to help your project so Iam just giving some tips that may or may not be added to it.**

**Comment by hahagu** [comment]
> ### **#1 The folder thumbnail could be similar to Windows 10 Version**

Changing the model to fit the Windows 10 version will require significant codebase rewrite.
Allowing different colors and stuff is one thing, a mock-3d effect is another.
Honestly, I don't see it being implemented anytime soon without a complete rework.
Still debating on that, haha

> And
> ### **#2 Applying all at once instead of aplying one by one**
> 
> As far as I watched the tutorials and applied the model, I need to aply it for every single folder, instead it maybe could be done at once, like for every folder with pictures it could be aplied instead of doing it one by one.

I did not even know there were tutorials for my tool 😅
"Every folder with pictures at once", meaning for the whole drive?
Doing that would be very inefficient.
Maybe I can add a batch processing feature in the future.
I also have been thinking about having a filesystem watcher to watch a directory and automatically apply that way.

Regarding the status of the project,
the project is currently stalled due to several factors, including the fact that I have less time available for personal projects,
and that I lack motivation to continue the project.
It isn't like I earn money doing this, you know, and I don't think anyone wants to donate for something like this, haha.

But also, do know that I'm not giving up on the project just yet, probably, no promises 😄

**Comment by ghost** [comment]
> > ### **#1 The folder thumbnail could be similar to Windows 10 Version**
> 
> Changing the model to fit the Windows 10 version will require significant codebase rewrite. Allowing different colors and stuff is one thing, a mock-3d effect is another. Honestly, I don't see it being implemented anytime soon without a complete rework. Still debating on that, haha
> 
> > And
> > ### **#2 Applying all at once instead of aplying one by one**
> > As far as I watched the tutorials and applied the model, I need to aply it for every single folder, instead it maybe could be done at once, like for every folder with pictures it could be aplied instead of doing it one by one.
> 
> I did not even know there were tutorials for my tool 😅 "Every folder with pictures at once", meaning for the whole drive? Doing that would be very inefficient. Maybe I can add a batch processing feature in the future. I also have been thinking about having a filesystem watcher to watch a directory and automatically apply that way.
> 
> Regarding the status of the project, the project is currently stalled due to several factors, including the fact that I have less time available for personal projects, and that I lack motivation to continue the project. It isn't like I earn money doing this, you know, and I don't think anyone wants to donate for something like this, haha.
> 
> But also, do know that I'm not giving up on the project just yet, probably, no promises 😄

Yes there are some tutorials on YouTube using your tool, but your ReadMe at Wiki already gives a lot of information about how to use it. Anyway great project, it does his job. And personally I understand you also have your times and probably other important things to think about, always appreciate people who afford their time to create innovative software and help community.
