### ISSUE TITLE
Will generator replace chosen by me folder icon?

### ISSUE THREAD

**Issue by GKProduction** [hahagu/WindowsThumbnailGenerator#27]
If I chose the icon for the folder myself (from %SystemRoot%\System32\SHELL32.dll), will the WindowsThumbnailGenerator replace this folder icon with thumbnails icon or not?

**Comment by hahagu** [comment]
It will replace the icon with the generated folder icons :)

**Comment by GKProduction** [comment]
Oh no!

**Comment by hahagu** [comment]
If you wish to prevent the generator from overwriting desktop.ini files that already exist, you can check the `Skip Existing` option to skip those folders.

**Comment by GKProduction** [comment]
It changes everything. Thanks for letting me know! Also thank you for this useful tool 🌞
