### ISSUE TITLE
List and Details view icon a bit smaller than other folders

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [hahagu/WindowsThumbnailGenerator#4]
![image](https://user-images.githubusercontent.com/46422834/134134764-029de3b8-893a-4c4a-aa6e-704164c2a992.png)

List and Details view icon a bit smaller than other folders. Can you make it bigger? Add the yellow folder "padding" like a border on all sides of the thumbnail preview so it looks nicer.

**Comment by hahagu** [comment]
This is rather an issue with Windows 11's scaling system of images.
If I were to fix this, multiple images of various resolutions with various different icon shapes would need to be generated.
