### ISSUE TITLE
Feature Request: maximize visible Thumbnail area by completely removing cover image

### ISSUE THREAD

**Issue by InsaneDruid** [hahagu/WindowsThumbnailGenerator#8]
having an option to maximize the visible Thumbnail area by completely removing the cover image (lower yellow bar) would be very useful, especially in combination with the requested feature of parsing existing folder.image entries.

**Comment by hahagu** [comment]
Completely doable.

As for the folder image entry, how do you reckon it is implemented?
I could have the program prioritize folder.jpg/folder.png if they exist, and not use any other images if they do exist.

**Comment by InsaneDruid** [comment]
yea that sounds reasonable
